platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Trackerman' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trackerman

  target 'TrackermanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackermanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
